---
galaxy_info:
  role_name: docker
  author: zdarovayrodi
  description: Install Docker and run container
  license: MIT
  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - focal

  galaxy_tags:
    - docker
    - container
    - application

dependencies: [] 