---
# Базовые настройки PostgreSQL
postgresql_version: "14"
postgresql_data_dir: "/var/lib/postgresql/14/main"
postgresql_listen_addresses: "*"
postgresql_port: 5432
postgresql_max_connections: 100
postgresql_shared_buffers: "256MB"

# Настройки репликации
postgresql_is_master: true
postgresql_replica_user: "replicator"
postgresql_replica_password: "strong_replication_password"

# Пример создания базы данных и пользователя
postgresql_databases:
  - name: myapp
    owner: myapp_user

postgresql_users:
  - name: myapp_user
    password: "secure_password"
    privileges: ALL
    database: myapp 