---
# Prometheus configuration
prometheus_web_listen_address: "0.0.0.0:9090"
prometheus_storage_retention: "30d"
prometheus_targets:
  - targets:
      - "app:8080"
    labels:
      env: production
      job: spring-boot

# Grafana configuration
grafana_security:
  admin_user: admin
  admin_password: admin
grafana_datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: true
  - name: Loki
    type: loki
    access: proxy
    url: http://localhost:3100
    isDefault: false

# Loki configuration
loki_config_dir: /etc/loki
loki_listen_address: "0.0.0.0:3100" 