Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # node 1
  config.vm.define "app1" do |app1|
    app1.vm.hostname = "app1"
    app1.vm.network "private_network", ip: "192.168.56.11"
    app1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

  # node 2
  config.vm.define "app2" do |app2|
    app2.vm.hostname = "app2"
    app2.vm.network "private_network", ip: "192.168.56.12"
    app2.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end
end
