Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # Определение машин
  APP_HOST = "app"
  DB_HOST = "db"
  
  def create_host(config, hostname, ip)
    config.vm.define hostname do |host|
      host.vm.network "private_network", ip: ip
      host.vm.hostname = hostname
      host.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
      end
      host.vm.provision "shell", inline: "apt-get update && apt-get install -y python3"
    end
  end

  # Создание машины для приложения
  create_host(config, APP_HOST, "192.168.56.10")

  # Создание машины для базы данных
  create_host(config, DB_HOST, "192.168.56.11")
end
