Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # Конфигурация машины для приложения
  config.vm.define "app" do |app|
    app.vm.hostname = "app"
    app.vm.network "private_network", ip: "192.168.56.10"
    app.vm.network "forwarded_port", guest: 8080, host: 8080
    app.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
  end

  # Конфигурация машины для мониторинга
  config.vm.define "monitoring" do |monitoring|
    monitoring.vm.hostname = "monitoring"
    monitoring.vm.network "private_network", ip: "192.168.56.11"
    # Порты для Grafana, Prometheus и Loki
    monitoring.vm.network "forwarded_port", guest: 3000, host: 3000  # Grafana
    monitoring.vm.network "forwarded_port", guest: 9090, host: 9090  # Prometheus
    monitoring.vm.network "forwarded_port", guest: 3100, host: 3100  # Loki
    monitoring.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 2
    end
  end

  # Общие настройки для всех машин
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y python3 python3-pip
  SHELL
end
