---
docker_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - python3-docker

container_name: django-app
container_image: timurbabs/django
container_port: 8000

django_debug: "True"
django_secret_key: django-insecure-key-for-dev
django_db_url: sqlite:///db.sqlite3

admin_username: admin
admin_email: admin@example.com
admin_password: adminpass123 