---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Install python3 and required packages
      raw: apt-get update && apt-get install -y python3 python3-apt aptitude sudo
      changed_when: false 